### ISSUE TITLE
per instance Scripty cache

### ISSUE THREAD

**Issue by behrad** [TheDeveloper/scripty#1]
using a global cache https://github.com/TheDeveloper/scripty/blob/master/lib/Scripty.js#L16 prevents from closing the redis client and create a new Scripty with a new redis client object.

**Comment by TheDeveloper** [comment]
is your new redis client connected to a different redis server?

**Comment by behrad** [comment]
no the same server, but different object instance, I'm closing old instance and creating new one :)
this is happening when gracefully shutdown kue: https://github.com/Automattic/kue/issues/578

**Comment by behrad** [comment]
look at this example code: https://github.com/TheDeveloper/warlock/issues/11#issue-65688222

**Comment by behrad** [comment]
generally caching a user/client provided instance object (the redis client) is a bad idea along side `Script` object.

**Comment by TheDeveloper** [comment]
oh yes I see, the redis client object is being cached along with the script. will merge your PR.

**Comment by behrad** [comment]
thank you @TheDeveloper

**Comment by behrad** [comment]
when can I switch to your npm?

**Comment by TheDeveloper** [comment]
just published [v0.0.5](https://www.npmjs.com/package/node-redis-scripty) :)

warlock will pick up the latest version

**Comment by behrad** [comment]
:+1:
